#!/bin/bash -f

# simvascular specific additions

export SOFTWARE_PLATFORM=REPLACEME_SOFTWARE_PLATFORM
export COMPILER_VERSION=REPLACEME_COMPILER_VERSION
export SV_OS=REPLACEME_SV_OS

# must specify paths in unix style
export OPEN_SOFTWARE_BINARIES_TOPLEVEL=REPLACEME_OPEN_SOFTWARE_BINARIES_TOPLEVEL
export LICENSED_SOFTWARE_TOPLEVEL=REPLACEME_LICENSED_SOFTWARE_TOPLEVEL
export SV_HOME=REPLACEME_SV_HOME

# MeshSim license file
export SIM_LICENSE_FILE=REPLACEME_LICENSE_FILE
export SIM_LICENSE_FILE=$SV_HOME/Licenses/MeshSim/license.dat

# 3-D solver environment variables
export FLOWSOLVER_CONFIG=$SV_HOME/Code/FlowSolvers/ThreeDSolver/svSolver
export LES_LICENSE_SERVER=$SV_HOME/Licenses/LesLib/license.dat
#export LES_LICENSE_SERVER=foo.bar.edu

################################################################
# YOU PROBABLY DON'T NEED TO CHANGE ANYTHING BELOW THIS LINE.  #
#                                                              # 
# NOTE:  This file needs to be kept current with changes in    #
# paths found in include.mk                                    #
#                                                              # 
################################################################

# simvascular addition
export LD_LIBRARY_PATH=$SV_HOME/Code/Lib:$LD_LIBRARY_PATH

# need to convert to dos style paths on windows
case "$SV_OS" in
 "windows" )
export SV_HOME=`cygpath --windows -t mixed $SV_HOME`
export OPEN_SOFTWARE_BINARIES_TOPLEVEL=`cygpath --windows -t mixed $OPEN_SOFTWARE_BINARIES_TOPLEVEL`
export LICENSED_SOFTWARE_TOPLEVEL=`cygpath --windows -t mixed $OPEN_SOFTWARE_BINARIES_TOPLEVEL`
export FLOWSOLVER_CONFIG=`cygpath --windows -t mixed $FLOWSOLVER_CONFIG`
export LES_LICENSE_SERVER=`cygpath --windows -t mixed $LES_LICENSE_SERVER`
export PATH=$LD_LIBRARY_PATH:$PATH
;;
esac

# run the executable
/cygdrive/c/Program\ Files/Microsoft\ MPI/Bin/mpiexec.exe -np $1 -env FLOWSOLVER_CONFIG $FLOWSOLVER_CONFIG $SV_HOME/BuildWithMake/Bin/flowsolver.exe $2 $3 $4
