set(Plugin-Name "Demo Example Plugin")
set(Plugin-Version "0.1")
set(Plugin-Vendor "Awesome Company")
set(Plugin-ContactAddress "http://www.demoproject.my")
set(Require-Plugin org.mitk.gui.qt.common)
