set(Plugin-Name "SimVascular Python DataNodes")
set(Plugin-Version "1.0")
set(Plugin-Vendor "Stanford Medicine")
set(Plugin-ContactAddress "http://www.simvascular.org")
set(Require-Plugin org.mitk.gui.common)
set(Plugin-ActivationPolicy "eager")
