#!/bin/bash -f

export SV_HOME=/usr/local/package/REPLACE_SV_VERSION/REPLACE_TIMESTAMP
export SV_RELEASE_BUILD=REPLACE_SV_PLATFORM

################################################################
# YOU PROBABLY DON'T NEED TO CHANGE ANYTHING BELOW THIS LINE.  #
################################################################

export SV_STATIC_BUILD=1
export SV_RELEASED_MODE=1

# SV additions (parasolid, tcltk, etc.)
export LD_LIBRARY_PATH=$SV_HOME:$LD_LIBRARY_PATH

# MeshSim license file
export SIM_LICENSE_FILE=$SV_HOME/meshsim-license.dat

# Tcl/Tk additions
export TCL_LIBRARY=$SV_HOME/lib/REPLACE_TCL_VERSION_NO
export TK_LIBRARY=$SV_HOME/lib/REPLACE_TK_VERSION_NO
export LD_LIBRARY_PATH=$SV_HOME/lib:$LD_LIBRARY_PATH

# PARASOLID additions
export P_SCHEMA=$SV_HOME/schema

# MPICH2 additions
export LD_LIBRARY_PATH=$SV_HOME/mpi/lib:$LD_LIBRARY_PATH

# intel additions
export LD_LIBRARY_PATH=$SV_HOME/intel_compiler_runtime_libs:$LD_LIBRARY_PATH

