#!/bin/bash -f

export SIMVASCULAR_HOME=/usr/local/package/REPLACE_SIMVASCULAR_VERSION/REPLACE_TIMESTAMP
export SIMVASCULAR_RELEASE_BUILD=REPLACE_SIMVASCULAR_PLATFORM

################################################################
# YOU PROBABLY DON'T NEED TO CHANGE ANYTHING BELOW THIS LINE.  #
################################################################

export SIMVASCULAR_STATIC_BUILD=1
export SIMVASCULAR_RELEASED_MODE=1

# SV additions (parasolid, tcltk, etc.)
export LD_LIBRARY_PATH=$SIMVASCULAR_HOME:$LD_LIBRARY_PATH

# MeshSim license file
export SIM_LICENSE_FILE=$SIMVASCULAR_HOME/meshsim-license.dat

# Tcl/Tk additions
export TCL_LIBRARY=$SIMVASCULAR_HOME/lib/REPLACE_TCL_VERSION_NO
export TK_LIBRARY=$SIMVASCULAR_HOME/lib/REPLACE_TK_VERSION_NO
export LD_LIBRARY_PATH=$SIMVASCULAR_HOME/lib:$LD_LIBRARY_PATH

# PARASOLID additions
export P_SCHEMA=$SIMVASCULAR_HOME/schema

# MPICH2 additions
export LD_LIBRARY_PATH=$SIMVASCULAR_HOME/mpi/lib:$LD_LIBRARY_PATH

# intel additions
export LD_LIBRARY_PATH=$SIMVASCULAR_HOME/intel_compiler_runtime_libs:$LD_LIBRARY_PATH

