set(Plugin-Name "SimVascular Path Planning")
set(Plugin-Version "1.0")
set(Plugin-Vendor "Stanford Medicine")
set(Plugin-ContactAddress "http://www.simvascular.org")
set(Require-Plugin org.mitk.gui.qt.common.legacy org.mitk.gui.qt.common org.mitk.gui.qt.datamanager)
#set(Plugin-ActivationPolicy "eager")
