ifeq ($(CLUSTER), x64_cygwin)
    LESLIB_DEFS   = -DACUSIM_NT -DACUSIM_WIN -DACUSIM_WIN64
    LESLIB_INCDIR = -I $(LESLIB_TOP)
    LESLIB_TOP    = $(LICENSED_SOFTWARE_TOPLEVEL)/leslib-1.5/win/x64
    LESLIB_LIBS   = $(LIBPATH_COMPILER_FLAG)$(LESLIB_TOP) $(LIBFLAG)libles.lib
    LESLIB_LIBS  += $(LIBFLAG)Advapi32.lib $(LIBFLAG)Ws2_32.lib
endif
