ifeq ($(CLUSTER), x64_macosx)
    OPENCASCADE_SRCDIR = $(OPEN_SOFTWARE_SOURCES_TOPLEVEL)/opencascade-7.0.0
    OPENCASCADE_BINDIR = $(OPEN_SOFTWARE_BINARIES_TOPLEVEL)/opencascade-7.0.0
    OPENCASCADE_INCDIR   = -I$(OPENCASCADE_BINDIR)/include/opencascade
    ifeq ($(MAKE_WITH_OPENCASCADE_SHARED),1)
      OPENCASCADE_LIBDIR   = $(OPENCASCADE_BINDIR)/lib
    else
      OPENCASCADE_LIBDIR   = $(OPENCASCADE_BINDIR)/lib
    endif
    SV_OPENCASCADE_SO_PATH  = $(OPENCASCADE_BINDIR)/lib
    OPENCASCADE_LIBS     = $(LIBPATH_COMPILER_FLAG)$(OPENCASCADE_LIBDIR) \
	$(LIBFLAG)FWOSPlugin$(LIBLINKEXT) \
	$(LIBFLAG)TKBin$(LIBLINKEXT) \
	$(LIBFLAG)TKBinL$(LIBLINKEXT) \
	$(LIBFLAG)TKBinTObj$(LIBLINKEXT) \
	$(LIBFLAG)TKBinXCAF$(LIBLINKEXT) \
	$(LIBFLAG)TKBO$(LIBLINKEXT) \
	$(LIBFLAG)TKBool$(LIBLINKEXT) \
	$(LIBFLAG)TKBRep$(LIBLINKEXT) \
	$(LIBFLAG)TKCAF$(LIBLINKEXT) \
	$(LIBFLAG)TKCDF$(LIBLINKEXT) \
	$(LIBFLAG)TKernel$(LIBLINKEXT) \
	$(LIBFLAG)TKFeat$(LIBLINKEXT) \
	$(LIBFLAG)TKFillet$(LIBLINKEXT) \
	$(LIBFLAG)TKG2d$(LIBLINKEXT) \
	$(LIBFLAG)TKG3d$(LIBLINKEXT) \
	$(LIBFLAG)TKGeomAlgo$(LIBLINKEXT) \
	$(LIBFLAG)TKGeomBase$(LIBLINKEXT) \
	$(LIBFLAG)TKHLR$(LIBLINKEXT) \
	$(LIBFLAG)TKIGES$(LIBLINKEXT) \
	$(LIBFLAG)TKIVtk$(LIBLINKEXT) \
	$(LIBFLAG)TKLCAF$(LIBLINKEXT) \
	$(LIBFLAG)TKMath$(LIBLINKEXT) \
	$(LIBFLAG)TKMesh$(LIBLINKEXT) \
	$(LIBFLAG)TKMeshVS$(LIBLINKEXT) \
	$(LIBFLAG)TKOffset$(LIBLINKEXT) \
	$(LIBFLAG)TKOpenGl$(LIBLINKEXT) \
	$(LIBFLAG)TKPrim$(LIBLINKEXT) \
	$(LIBFLAG)TKService$(LIBLINKEXT) \
	$(LIBFLAG)TKShHealing$(LIBLINKEXT) \
	$(LIBFLAG)TKStd$(LIBLINKEXT) \
	$(LIBFLAG)TKStdL$(LIBLINKEXT) \
	$(LIBFLAG)TKSTEP$(LIBLINKEXT) \
	$(LIBFLAG)TKSTEP209$(LIBLINKEXT) \
	$(LIBFLAG)TKSTEPAttr$(LIBLINKEXT) \
	$(LIBFLAG)TKSTEPBase$(LIBLINKEXT) \
	$(LIBFLAG)TKSTL$(LIBLINKEXT) \
	$(LIBFLAG)TKTObj$(LIBLINKEXT) \
	$(LIBFLAG)TKTopAlgo$(LIBLINKEXT) \
	$(LIBFLAG)TKV3d$(LIBLINKEXT) \
	$(LIBFLAG)TKVCAF$(LIBLINKEXT) \
	$(LIBFLAG)TKVRML$(LIBLINKEXT) \
	$(LIBFLAG)TKXCAF$(LIBLINKEXT) \
	$(LIBFLAG)TKXDEIGES$(LIBLINKEXT) \
	$(LIBFLAG)TKXDESTEP$(LIBLINKEXT) \
	$(LIBFLAG)TKXMesh$(LIBLINKEXT) \
	$(LIBFLAG)TKXml$(LIBLINKEXT) \
	$(LIBFLAG)TKXmlL$(LIBLINKEXT) \
	$(LIBFLAG)TKXmlTObj$(LIBLINKEXT) \
	$(LIBFLAG)TKXmlXCAF$(LIBLINKEXT) \
	$(LIBFLAG)TKXSBase$(LIBLINKEXT)
endif
