ifeq ($(CLUSTER), x64_cygwin)
    PYTHON_BASE   = C:/OpenSource/Python-2.7
    PYTHON_SRCDIR = 
    PYTHON_BINDIR = $(PYTHON_BASE)/bin
    SV_PYTHON_SO_PATH = $(PYTHON_BINDIR)
    PYTHON_INCDIR = -I$(PYTHON_BASE)/include
    PYTHON_LIBDIR = $(PYTHON_BASE)/libs
    PYTHON_LIB    = $(LIBPATH_COMPILER_FLAG)$(PYTHON_LIBDIR) $(LIBFLAG)python27$(LIBLINKEXT)
   PYTHON_SITE_PACKAGES = $(PYTHON_BASE)/Lib/site-packages
endif
