ifeq ($(CLUSTER), x64_cygwin)
    PYTHON_HOME   =  $(OPEN_SOFTWARE_BINARIES_TOPLEVEL)/python-2.7.11
    PYTHON_SRCDIR = 
    PYTHON_BINDIR = $(PYTHON_HOME)/bin
    SV_PYTHON_SO_PATH = $(PYTHON_BINDIR)
    PYTHON_INCDIR = -I$(PYTHON_HOME)/include
    PYTHON_LIBDIR = $(PYTHON_HOME)/libs
    PYTHON_LIB    = $(LIBPATH_COMPILER_FLAG)$(PYTHON_LIBDIR) $(LIBFLAG)python27$(LIBLINKEXT)
    PYTHON_SITE_PACKAGES = $(PYTHON_HOME)/Lib\;$(PYTHON_HOME)/Lib/site-packages
endif
