ifeq ($(CLUSTER), x64_linux)
    ZLIB_TOPLEVEL = $(OPEN_SOFTWARE_BINARIES_TOPLEVEL)/zlib-1.2.3
    ZLIB_INCDIR = -I $(ZLIB_TOPLEVEL)
    ZLIB_LIBDIR = $(ZLIB_TOPLEVEL)
    ZLIB_LIBS   = $(ZLIB_LIBDIR)/libz.a
endif
