set(CPP_FILES
  mitkCalculateSegmentationVolume.cpp
  mitkContourModelSetToImageFilter.cpp
  mitkContourSetToPointSetFilter.cpp
  mitkContourUtils.cpp
  mitkCorrectorAlgorithm.cpp
  mitkDiffImageApplier.cpp
  mitkDiffSliceOperation.cpp
  mitkDiffSliceOperationApplier.cpp
  mitkFeatureBasedEdgeDetectionFilter.cpp
  mitkImageLiveWireContourModelFilter.cpp
  mitkImageToContourFilter.cpp
  #mitkImageToContourModelFilter.cpp
  mitkImageToLiveWireContourFilter.cpp
  mitkManualSegmentationToSurfaceFilter.cpp
  mitkOtsuSegmentationFilter.cpp
  mitkOverwriteDirectedPlaneImageFilter.cpp
  mitkOverwriteSliceImageFilter.cpp
  mitkSegmentationObjectFactory.cpp
  mitkShapeBasedInterpolationAlgorithm.cpp
  mitkShowSegmentationAsSmoothedSurface.cpp
  mitkShowSegmentationAsSurface.cpp
  mitkVtkImageOverwrite.cpp
  mitkSegmentationInterpolationController.cpp
  mitkToolManager.cpp
  mitkSegmentationModuleActivator.cpp
  mitkToolManagerProvider.cpp
  mitkContour.cpp
  #mitkContourElement.cpp
  #mitkContourModel.cpp
  mitkContourSet.cpp
  mitkExtrudedContour.cpp
  mitkAdaptiveRegionGrowingTool.cpp
  mitkAddContourTool.cpp
  mitkAutoCropTool.cpp
  mitkAutoSegmentationTool.cpp
  mitkBinaryThresholdTool.cpp
  mitkBinaryThresholdULTool.cpp
  mitkCalculateGrayValueStatisticsTool.cpp
  mitkCalculateVolumetryTool.cpp
  mitkContourModelInteractor.cpp
  mitkContourModelLiveWireInteractor.cpp
  mitkLiveWireTool2D.cpp
  mitkContourTool.cpp
  mitkCorrectorTool2D.cpp
  mitkCreateSurfaceTool.cpp
  mitkDrawPaintbrushTool.cpp
  mitkErasePaintbrushTool.cpp
  mitkEraseRegionTool.cpp
  mitkFastMarchingTool.cpp
  mitkFastMarchingTool3D.cpp
  mitkFeedbackContourTool.cpp
  mitkFillRegionTool.cpp
  mitkOtsuTool3D.cpp
  mitkPaintbrushTool.cpp
  mitkPixelManipulationTool.cpp
  mitkRegionGrowingTool.cpp
  mitkSegmentationsProcessingTool.cpp
  mitkSetRegionTool.cpp
  mitkSegTool2D.cpp
  mitkSubtractContourTool.cpp
  mitkTool.cpp
  mitkToolCommand.cpp
  mitkWatershedTool.cpp
  mitkPickingTool.cpp
  mitkSegmentationInteractor.cpp #SO
  #IO/mitkContourModelIOFactory.cpp
  #IO/mitkContourModelReader.cpp
  #IO/mitkContourModelWriter.cpp
  #IO/mitkContourModelWriterFactory.cpp
  mitkContourMapper2D.cpp
  #mitkContourModelGLMapper2D.cpp
  #mitkContourModelMapper2D.cpp
  #mitkContourModelMapper3D.cpp
  mitkContourSetMapper2D.cpp
  mitkContourSetVtkMapper3D.cpp
  mitkContourVtkMapper3D.cpp
  mitkBooleanOperation.cpp
  mitkMorphologicalOperations.cpp
#Added from ML
  mitkSliceBasedInterpolationController.cpp
  mitkSurfaceStampImageFilter.cpp
)

set(RESOURCE_FILES
  Add_48x48.png
  Add_Cursor_32x32.png
  Correction_48x48.png
  Correction_Cursor_32x32.png
  Erase_48x48.png
  Erase_Cursor_32x32.png
  FastMarching_48x48.png
  FastMarching_Cursor_32x32.png
  Fill_48x48.png
  Fill_Cursor_32x32.png
  LiveWire_48x48.png
  LiveWire_Cursor_32x32.png
  Otsu_48x48.png
  Paint_48x48.png
  Paint_Cursor_32x32.png
  Pick_48x48.png
  RegionGrowing_48x48.png
  RegionGrowing_Cursor_32x32.png
  Subtract_48x48.png
  Subtract_Cursor_32x32.png
  Threshold_48x48.png
  TwoThresholds_48x48.png
  Watershed_48x48.png
  Watershed_Cursor_32x32.png
  Wipe_48x48.png
  Wipe_Cursor_32x32.png

  Interactions/dummy.xml
  Interactions/LiveWireTool.xml
  Interactions/FastMarchingTool.xml
  Interactions/PressMoveRelease.xml
  Interactions/PressMoveReleaseAndPointSetting.xml
  Interactions/PressMoveReleaseWithCTRLInversion.xml
  Interactions/PressMoveReleaseWithCTRLInversionAllMouseMoves.xml
  Interactions/SegmentationToolsConfig.xml

  Interactions/ContourModelModificationConfig.xml
  Interactions/ContourModelModificationInteractor.xml
)
