set(CPP_FILES
  mitkContourModelSource.cpp
  mitkContourModelSetSource.cpp
  mitkContourModelSubDivisionFilter.cpp
  mitkContourModelToPointSetFilter.cpp
  mitkContourModelToSurfaceFilter.cpp
  mitkImageToContourModelFilter.cpp
  mitkContourObjectFactory.cpp
  mitkContourModelUtils.cpp
  mitkContourModel.cpp
  mitkContourModelSet.cpp
  mitkContourElement.cpp
  mitkContourModelGLMapper2D.cpp
  mitkContourModelMapper2D.cpp
  mitkContourModelMapper3D.cpp
  mitkContourModelSetMapper3D.cpp
  mitkContourModelSetGLMapper2D.cpp
  mitkContourModelGLMapper2DBase.cpp
  mitkContourModelSerializer.cpp
  mitkContourModelReader.cpp
  mitkContourModelWriter.cpp
  mitkContourModelSetSerializer.cpp
  mitkContourModelSetReader.cpp
  mitkContourModelSetWriter.cpp
  mitkContourModelActivator.cpp
)
