set(Plugin-Name "SimVascular svFSI")
set(Plugin-Version "1.0")
set(Plugin-Vendor "Stanford Medicine")
set(Plugin-ContactAddress "http://www.simvascular.org")
set(Require-Plugin org.mitk.gui.qt.common.legacy org.mitk.gui.qt.common org.sv.gui.qt.datamanager)
