if(Qt5_DIR)
  get_filename_component(_Qt5_DIR "${Qt5_DIR}/../../../" ABSOLUTE)
  if(${CMAKE_PROJECT_NAME}_ENABLE_DISTRIBUTION)
    set(LIB_DESTINATION "${SV_EXTERNALS_INSTALL_PREFIX}")
  else()
    set(LIB_DESTINATION "${SV_EXTERNALS_INSTALL_PREFIX}/Qt5")
  endif()
  if(${CMAKE_PROJECT_NAME}_ENABLE_DISTRIBUTION)
    if(EXISTS ${_Qt5_DIR}/lib)
      install(DIRECTORY ${_Qt5_DIR}/lib DESTINATION ${LIB_DESTINATION})
    endif()
    if(EXISTS ${_Qt5_DIR}/bin)
      install(DIRECTORY ${_Qt5_DIR}/bin DESTINATION ${LIB_DESTINATION})
    endif()
    if(EXISTS ${_Qt5_DIR}/plugins)
      simvascular_get_subdirs(_Qt5_SUBDIRS "${_Qt5_DIR}/plugins")
      foreach(subdir ${_Qt5_SUBDIRS})
        install(DIRECTORY "${_Qt5_DIR}/plugins/${subdir}" DESTINATION ${SV_INSTALL_RUNTIME_DIR})
      endforeach()
    endif()
  endif()
endif()
