set(Plugin-Name "SimVascular Application")
set(Plugin-Version "1.0.0")
set(Plugin-Vendor "Stanford Medicine")
set(Plugin-ContactAddress "http://www.simvascular.org")
set(Require-Plugin org.mitk.gui.qt.extapplication)
