name: macos
on: [push, pull_request]
jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: pwsh
        run: |
          choco install cygwin --params "/InstallDir:C:/cygwin64"
          choco install cyg-get wget visualstudio2017community
          cyg-get make tclsh zip gzip tar date patch startxwin
          "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
          "C:/cygwin64/bin/bash.exe" --login -i
          cd BuildWithMake
          bash prep_windows.sh
          bash quick-build-windows.sh
          cd Release
          make
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows Installer
          path: BuildWithMake/Release/*.exe
          if-no-files-found: error