name: macos
on: [push, pull_request]
jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          choco install wget visualstudio2017community
          wget https://www.cygwin.com/setup-x86_64.exe
          ./setup-x86_64.exe --quiet-mode --disable-buggy-antivirus --no-desktop --download --no-verify --root C:/cygwin64 -s http://cygwin.mirrors.pair.com/
          ./setup-x86_64.exe --quiet-mode --disable-buggy-antivirus --no-desktop --download --no-verify --root C:/cygwin64 --packages make,tclsh,zip,gzip,tar,date,patch -s http://cygwin.mirrors.pair.com/
          cd BuildWithMake
          ./startX-with-2017.bat
          echo "which-CL"
          which CL
          bash prep_windows.sh
          bash quick-build-windows.sh
          cd Release
          make
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows Installer
          path: BuildWithMake/Release/*.exe
          if-no-files-found: error