name: macos
on: [push, pull_request]
jobs:
  build-windows:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - uses: cygwin/cygwin-install-action@master
        with:
          install-dir: C:\cygwin64
          packages: make tclsh zip gzip tar date patch
      - name: Build
        run: |
          choco install wget
          cd BuildWithMake
          C:\cygwin64\bin\bash.exe -c $'"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && which CL'
          C:\cygwin64\bin\bash.exe -c "which CL"
          C:\cygwin64\bin\bash.exe -c "prep_windows.sh"
          C:\cygwin64\bin\bash.exe -c "quick-build-windows.sh"
          cd Release
          make
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows Installer
          path: BuildWithMake/Release/*.exe
          if-no-files-found: error