name: Build
on: [push, pull_request]
jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Cygwin
        uses: cygwin/cygwin-install-action@master
        with:
          install-dir: C:\cygwin64
          packages: make tcl zip gzip tar patch wget
      - name: Install Visual Studio BuildTools
        run: |
          choco install visualstudio2017buildtools visualstudio2017-workload-vctools
      - name: Build
        run: |
          cd BuildWithMake
          dos2unix ./quick-build-windows.sh
          C:\cygwin64\bin\bash.exe -c "./build_windows_github.bat"
          cp Release/SimVascular-*-Windows-64bit-bundle.exe ../SimVascular-Windows.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows Installer
          path: SimVascular-Windows.exe
          if-no-files-found: error
      - name: Upload release asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: SimVascular-Windows.exe
          asset_name: SimVascular-${{github.ref_name}}-Windows.exe
          tag: ${{ github.ref }}
