name: macos
on: [push, pull_request]
jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: cygwin/cygwin-install-action@master
        with:
          install-dir: C:\cygwin64
          packages: make tclsh zip gzip tar date patch
      - name: Build
        shell: bash
        run: |
          C:\cygwin64\bin\bash --login
          choco install wget visualstudio2017community
          rm -r -f "C:\Program Files (x86)\Microsoft Visual Studio\2019"
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools"
          ./vsdevcmd -arch=x64
          cd D:\a\SimVascular\SimVascular\BuildWithMake
          echo "which-CL"
          which CL
          bash prep_windows.sh
          bash quick-build-windows.sh
          cd Release
          make
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows Installer
          path: BuildWithMake/Release/*.exe
          if-no-files-found: error