name: macos
on: [push, pull_request]
jobs:
  build-windows:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - uses: cygwin/cygwin-install-action@master
        with:
          install-dir: C:\cygwin64
          packages: make tclsh zip gzip tar date patch wget
      - name: Build
        run: |
          cd BuildWithMake
          dos2unix ./prep_windows.sh
          dos2unix ./quick-build-windows.sh
          dir "C:\Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/"
        # C:\cygwin64\bin\bash.exe -c "./build_windows.bat"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows Installer
          path: BuildWithMake/Release/*.exe
          if-no-files-found: error