name: macos
on: [push, pull_request]
jobs:
  # build-windows-2016:
  #   runs-on: windows-2016
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: cygwin/cygwin-install-action@master
  #       with:
  #         install-dir: C:\cygwin64
  #         packages: make tclsh zip gzip tar date patch wget
  #     - name: Build
  #       run: |
  #         cd BuildWithMake
  #         dos2unix ./quick-build-windows.sh
  #         C:\cygwin64\bin\bash.exe -c "./build_windows.bat"
  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: Windows Installer
  #         path: BuildWithMake/Bin/simvascular.exe
  #         if-no-files-found: error
  build-windows-2019:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: cygwin/cygwin-install-action@master
        with:
          install-dir: C:\cygwin64
          packages: make tcl zip gzip tar date patch wget
      - name: Install dependencies
        run: |
          choco install visualstudio2017buildtools visualstudio2017-workload-vctools
          dir "C:\Program Files (x86)\WiX Toolset v3.11"
          tree "C:\Program Files (x86)\WiX Toolset v3.11"
      - name: Build
        run: |
          cd BuildWithMake
          dos2unix ./quick-build-windows.sh
          C:\cygwin64\bin\bash.exe -c "./build_windows2019.bat"
          cd ..
          zip -r COMPLETE_FOLDER.zip BuildWithMake
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows Installer
          path: COMPLETE_FOLDER.zip
          if-no-files-found: error