name: macos
on: [push, pull_request]
jobs:
  build-windows-2016:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - uses: cygwin/cygwin-install-action@master
        with:
          install-dir: C:\cygwin64
          packages: make tclsh zip gzip tar date patch wget
      - name: Build
        run: |
          cd BuildWithMake
          dos2unix ./quick-build-windows.sh
          C:\cygwin64\bin\bash.exe -c "./build_windows.bat"
          tree
          cd ..
          tree
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows Installer
          path: BuildWithMake/Release/package
          if-no-files-found: error
  build-windows-2019:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: cygwin/cygwin-install-action@master
        with:
          install-dir: C:\cygwin64
          packages: make tclsh zip gzip tar date patch wget
      - name: Build
        run: |
          choco install visualstudio2017enterprise visualstudio2017buildtools
          cd BuildWithMake
          dos2unix ./quick-build-windows.sh
          C:\cygwin64\bin\bash.exe -c "./build_windows.bat"
          tree
          cd ..
          tree
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows Installer 2019
          path: BuildWithMake/Release/package
          if-no-files-found: error